[package]
name = "lottery-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.lottery]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.2"
